### ISSUE TITLE
Detect dependencies from import and pass options to Babel

### ISSUE THREAD

**Issue by jfairbank** [errbuddy/babel-asset-pipeline#1]
I've been evaluating this plugin and an alternative ([jurberg/es6to5-asset-pipeline](https://github.com/jurberg/es6to5-asset-pipeline)) for incorporating ES6 code into a grails project. The thing I like about this project is that it manages the Babel dependency on its own instead of requiring a globally available Babel along with a Node installation. The things I like about the other project is that detects `import` statements to manage asset dependencies and that I can control the options passed to the `babel` command. The other project looks dead at the moment, and its module system isn't ideal for my project. I would prefer to use a Babel plugin to transpile `import` and `export` into the appropriate calls for a different module system.

Would you consider incorporating those two features in this project: detecting `import` statements with `directivePattern` and allowing options to be passed to the Babel command? Thank you.

**Comment by peh** [comment]
hey.
options is already supported since 1.2 (but undocumented)
if you want to use it with grails you could set asset.config.babel.options to a map of options that is then passed to babels transform method ( see BabelProcessorSpec for a simple example ).

for importing require.js is needed. with r.js there is something that i may could use with rhino though i could not make it work till now.
But i tried it and i am totally planning to integrate it. till then i highly recommend to use asset-pipelines build in "require" mechanisms.

**Comment by jfairbank** [comment]
The options must be new because I don't recall seeing that in https://github.com/errbuddy/babel-asset-pipeline/blob/master/src/main/groovy/asset/pipeline/babel/BabelProcessor.groovy#L53 before.

As far as modules, I'm not a fan of require.js. I know this is your project, so you're free to use what you like, but I think being agnostic about the underlying module system would be better. What I meant by the `directivePattern` regex (https://github.com/errbuddy/babel-asset-pipeline/blob/master/src/main/groovy/asset/pipeline/babel/Es6AssetFile.groovy#L12) is that you could update it to support `import` statements in es6 files. That way the asset pipeline can do its job as normal. In other words, it would be nice to have `import foo from 'foo'` instead of just `//= require foo`.

These are just suggestions obviously. Thanks for adding the options feature by the way! :smile:

**Comment by peh** [comment]
i got your point. the problem is that babel transpiles imports into require("...")'s.
so require.js is needed and we would also need webpack or browserify to put everything together.

**Comment by jfairbank** [comment]
Yes, that's true. I would love to see a solution that uses webpack or browserify instead of what I'm doing. Currently, what I do is use a custom written module loader and custom plugin that translates the `import` statements into something besides `require('...')`. For example: `babel --plugins ./my-custom-module-plugin.js my-es6-file.js`. In my case the custom module loader is just a global object that holds references to all my modules for a given webpage.

**Comment by davydotcom** [comment]
Just a heads up there are other projects that use asset-pipeline that do NOT need to use webpack or browserify to do this. You can map the require calls with r.js and env.rhino.js to hit a static method and resolve with the asset pipelne internals which you will want to do anyway since assets may not be on the filesystem and could be in jars.

**Comment by kevana** [comment]
[Babel 6 removed the browser version](https://babeljs.io/docs/usage/browser/) so as far as I know we can't use the same "run in rhino and bridge to Java" pattern that other projects like the LESS plugin use.

Edit: @davydotcom I'm wrong, Looks like babel-standalone would be a drop-in replacement for the current version, wish I would've found out about this earlier.

**Comment by peh** [comment]
webpack (or browserify) is not supposed to be an replacement for "the old transpiler" as i said in #10 i would love to have webpack as an opt-in solution if you want all the fancy stuff that brings it (HMR and others).
as for r.js i played around with it alot but sadly never made it work, i am totally up for any improvements from you guys but currently my focus is fixing all the webpack issues and release it

**Comment by davydotcom** [comment]
To just give you guys a roadmap perspective. Im working on a module for asset-pipeline that provides webpack compatibility without any rhino or javascript runtime . Save for one thing ( I will never bundle css into your javascript ;) )

**Comment by peh** [comment]
will it support custom webpack configurations and loaders?

**Comment by kevana** [comment]
Will it support asset inheritance from plugins? And how are you planning on doing this? I'm really curious

**Comment by davydotcom** [comment]
we already support asset inheritence. it will basically tie into the existing Resolver conventions and Processor conventions of asset-pipeline to enable require() like directives to work.
