### ISSUE TITLE
Babel 6 migration strategy

### ISSUE THREAD

**Issue by kevana** [errbuddy/babel-asset-pipeline#10]
I think this plugin uses a version of Babel 5 committed [in the repo](https://github.com/errbuddy/babel-asset-pipeline/blob/master/src/main/resources/asset/pipeline/babel/babel.js). Babel 6 is out and I'd like to use it relatively soon. I see a couple options for us to support it, looking for feedback and discussion about the best way to do this:
### Have this plugin shell out to system babel

This is how the [es6to5-asset-pipeline](https://github.com/jurberg/es6to5-asset-pipeline/blob/master/src/groovy/asset/pipeline/es6to5/Es6to5Processor.groovy#L45) does it.
**Pro:** The asset-pipeline plugin no longer has to manage babel, users can use .babelrc and package.json files similar to other types of projects.
**Con:** Module ids could be tricky to do, devs will need to install node and babel locally, but in grails 3 there might be a way to keep everything in gradle with the gradle-node-plugin. 
### Include all babel packages in this repo.

**Pro:** Keeps this plugin self-contained like it currently is, devs don't need to have node and npm installed locally
**Con:** There are more than [100 babel packages](https://github.com/babel/babel/tree/master/packages), updates happen very often, and if a user wants to use an unofficial plugin they're out of luck.

**Comment by peh** [comment]
i thought about all that to and more or less gave up after some time.
i really don't want to force people to use a local node but i also want 6

so i thought about a hybrid!

what if we tell users: if you don't want to install node, you will have to stick with all the plugins we ship (that could be the most common  like es6 and react) and if they want more in it, they can do a request here).
But if they want to use more plugins and are willing to install node locally and on all dev's machines and on their buildserver (you can see why i don't liked that solution that much) they could opt in by setting some config flag in build.gradle.

implementation should be fairly easy ( i'm not sure gradle-node is the way to go as we need to call it from the processor and i would love to ship that option to grails-2 users too)

**Comment by kevana** [comment]
I like the hybrid idea, managing local node on dev and build boxes is a major pain.

I don't think the processor would need to be aware of gradle-node to use local node, but we'd probably need to tell it which node binary and babel entrypoint to use explicitly. e.g.:

System: 

```
grails.assets.babel.options.useSystem = true
grails.assets.babel.options.nodePath = '/usr/local/bin/node'
grails.assets.babel.options.babelPath = '/usr/local/bin/babel'
```

gradle-node: 

```
grails.assets.babel.options.useSystem = true
grails.assets.babel.options.nodePath = 'project/build/nodejs/node-v4.2.3-darwin-x64/bin/node'
grails.assets.babel.options.babelPath = 'project/node_modules/babel-core/index.js'
```

I think this would let them work together and stay self-contained on Grails 3 and still work with Grails 2.

**Comment by peh** [comment]
pushed some stuff to 
https://github.com/errbuddy/babel-asset-pipeline/tree/babel-npm
@kevana maybe you want to check it out, take a look and give me some feedback.

**Comment by kevana** [comment]
Code looks good, I have a couple concerns:
I think Browserify might break asset inheritance for plugins, unless we can get it to use asset-pipeline's resolver.
Potential duplicated dependencies, when Browserify has global project visibility it can build a bundle where common dependencies are only included once, but if A and B both include C and we process A and B separately, I think both files will end up packaged with a copy of C. If a project has 25 components that import React it could be an issue.

Without a browser version of Browserify to hook asset resolution into (like the less plugin), I'd be content with using babel-cli directly and punting on bundling with browserify. Our projects are set up to output AMD modules from babel and bundled with asset-pipeline manifests (see [kevana/grails-es6-mocha-demo](https://github.com/kevana/grails-es6-mocha-demo)). The bridge script to pull node_modules into the asset-pipeline world is a bit hacky, but plugin asset overrides still work.

**Comment by kevana** [comment]
Things that work:

---

## Using Browserify's require instead of asset-pipeline directives

i.e. `require('foo')` instead of `//= require foo`, this keeps us in the Browserify world and it de-dups structures like this:

```
// application.js
require('a.js')
require('b.js')
```

```
// a.js and b.js
require('c.js')
```

Only one copy of `c.js` gets included in the final bundle :+1: But I still think this breaks plugin inheritance :disappointed: 

---

## Using a client-side module loader

Tell Babel to output modules (using a `transform-es2015-modules-(amd|systemjs|umd)` plugin) and use asset-pipeline's require directives for bundling. Browserify doesn't try to suck in all of the file's dependencies lets asset-pipeline work its magic with inheritance. 

Our pattern for bootstrapping pages with modules:

```
# Directory structure, most files omitted
grails-app/assets/javascripts/
    application.js
    vendor/
        require.js
    core/
        changePassword/
            page.js
        changeAddress/
            page.js
        ...
```

```
// application.js bundle

//= require vendor/require.js
//= require_full_tree core
```

```
<script>
// Script on GSP 
require(['core/changePassword/page'], function(page) {
  page.init(${serverSideModel.initialState})
}
</script>
```

It's a bit more work than including a Browserify script that runs automatically:

```
<asset:script src="core/changePassword/page"/>
```

But, it works and doesn't break inheritance.

**Comment by kevana** [comment]
Hey @peh, do you need help with the `babel-npm` branch (review, testing, etc) before a release? I think it'd be cool if we got it released before [GR8Conf](http://gr8conf.us/#/).

**Comment by peh** [comment]
hey. actually i just wanted to write you today on slack whether you want to check it out :)
so yes some testing and reviewing would be great. 
for a reference usage you can check https://github.com/peh/babel-test-app
the most important part is using the taglib ( https://github.com/peh/babel-test-app/blob/master/grails-app/views/index.gsp ) 
which enables hot reloading with webpack hmr (only in develop and only if configured to be used, otherwise it just runs webpack and reads back the output (sadly webpack can only output into a file)
all this means that asset-pipelines dependencies system is ignored completly (no //= require ...).
ping me on slack if you need help setting things up. i am right now wrapping up documentation

**Comment by kevana** [comment]
And we shipped, I'm back. I'll try to post things as I find them.
- [WebpackBabelifier.groovy#L26](https://github.com/errbuddy/babel-asset-pipeline/blob/babel-npm/src/main/groovy/babel/asset/pipeline/WebpackBabelifier.groovy#L25), [babel-webpack.js#L22](https://github.com/peh/gradle-babel-asset-pipeline-helper/blob/master/babel-webpack.js#L22): Error messages are swallowed, the helper is printing to stdout and the java side is reading stderr.
- Webpack doesn't look at `.es6` files by default like v1 did, that's what caused my original error above. I think `resolve.extensions` in the generated webpack config would fix this.
- Would it make sense to match versions of babel-asset-pipeline and the helper npm module to hint at compatibility? (i.e. release both with the same version tag, `2.0.0`)
- Environments. We can use different webpack configs per environment with the `externalWebpackConfig` option, but usually there's only one `.babelrc` file. I think it'd be nice to set NODE_ENV somewhere along the line so we can do per-env config there too.

I can take a look at some of these, just wanted to get them written down before I forgot anything. Haven't tried the HMR yet.

**Comment by kevana** [comment]
Another one for future optimization, starting a new node process for every asset is a lot of work (starting node takes ~45ms on my laptop), it might make sense to move to a webpack-compiler-server pattern even if you're not using HMR in the future.

**Comment by peh** [comment]
thank you for those thoughts kevin,
- i created some stream logger that is now in charge of INFO/ERROR logging everything coming from webpack
- will push the fixed (2.0.0) version of the helper npm module in a second which also has the resolver addition
- added `nodeEnv` as a configuration parameter which is added to the webpack processes environment as "NODE_ENV=$nodeEnv" so set it to whatever you wish. i could only test it a bit but it looks like it works

what do you mean with "webpack-compiler-server pattern". it sounds like something that would be nice to have as i am also a bit annoyed that we have to spin up webpack over and over again :)

**Comment by peh** [comment]
missclicked... ^^^

**Comment by kevana** [comment]
For dev mode I think we could always run with the webpack-dev-server, I think it might be useful even with HMR turned off.

**Comment by kevana** [comment]
Another one, I think nodeExec in runtime YAML config requires an absolute path right now, something that's difficult to provide when using a custom location (e.g. `<project_dir>/.gradle/nodejs` for gradle-node-plugin). Is there a way to access to the project's directory inside the Babelifier to set the current working directory for the execute statement?

Goal:

yaml config:

```
nodeExec: build/nodejs/<node_version>/bin/node
```

In the buildscript we can access it pretty easily, but that doesn't help much with local development.

```
grails.assets.babel.nodeExec = "${project.buildDir}/.gradle/nodejs/<node_version>/bin/node"
```

**Comment by kevana** [comment]
I didn't know this existed: https://github.com/Daniel15/babel-standalone

**Comment by kevana** [comment]
Looks like it has Babel 6 and bundles all of the standard plugins. We could probably sidestep a lot of complexity by using this, the only thing we'd lose is Webpack. Thoughts?

**Comment by peh** [comment]
will check it later. the last time i tried it it was to big in for rhino (freaking 64k limit of java classes).
i can totally see that we still support the "non-node" transpiling like it is right now and just have webpack as an opt-in (exactly like now)

**Comment by kevana** [comment]
Oh, I didn't know there was a 64k limit, that sucks.

**Comment by peh** [comment]
yeah but i never tried babel-standalone. it was always some "self compiled" babel 6 hacks...

**Comment by kevana** [comment]
The minified version is 189k gzipped, 649k plaintext, doesn't look promising. But there might be a chance [with Nashorn](http://mail.openjdk.java.net/pipermail/nashorn-dev/2014-January/002710.html)
