### ISSUE TITLE
Switching to Nashorn

### ISSUE THREAD

**Issue by gferon** [errbuddy/babel-asset-pipeline#15]
I was wondering why you used Rhino when Nashorn is available in JDK >= 8, and has (AFAIK) much better performance. If you see no downside to this, I think I'll try to make the change and submit a PR.

**Comment by kevana** [comment]
Grails 3 supports Java 1.7+, if we'd like to maintain the same level of support for the plugin then we can't drop Rhino yet. But I don't know what real-world usage stats are. My company is on Java 8 for all of our Grails apps.

**Comment by peh** [comment]
grails-2 java 8 support is super bumpy that's why i have not updated yet.
if you want you could checkout the babel-npm branch and just implement a new Babelifier for Rhino.
i am totally open to that!

**Comment by gferon** [comment]
This is true, springloaded breaks in horrible ways with Java 8.
