### ISSUE TITLE
Support for grails 3.0.3

### ISSUE THREAD

**Issue by sanketmaru** [errbuddy/babel-asset-pipeline#2]
I added the dependency    **compile 'net.errbuddy.plugins:babel-asset-pipeline:1.3.0'**  in my build.gradle file but dependency is not getting downloaded.

Is the support for grails 3.0.3 supported ?

I want the jsx transformer and es6 to es5 to work with grails 3.0.3

**Comment by peh** [comment]
hey,
can you add "http://dl.bintray.com/errbuddy/plugins" to your repositories. this should fix it!

**Comment by sanketmaru** [comment]
Hey ,

Thanks for updating Readme file , I have got the jar downloaded. 

What configurations i need to do for transforming jsx files ? I gave the configurations in application.yml as 

asset:
        babel:
            processJsFiles: true
            enabled: true

Is that correct ?

**Comment by peh** [comment]
by default the plugin is only parsing ".es6" files
as you have already enabled "processJsFiles" any ".js" file is processed.
but ".jsx" is never handled

**Comment by sanketmaru** [comment]
my .js files has the jsx code , but it isn't transforming when the war is generated.

Does this plugin only converts the es6 to es5 ?

**Comment by peh** [comment]
2 things
do you have the asset-pipeline plugin activated?
can you please try to rename the file extension to .es6

actually babel.js has jsx transformation build in so it should just work

**Comment by sanketmaru** [comment]
@peh 

renaming the files extension to .es6 worked. 
Thanks for the help.
