### ISSUE TITLE
cannot pass presets to transformer

### ISSUE THREAD

**Issue by atript8** [errbuddy/babel-asset-pipeline#22]
I'm on Grails 2.5.5 and JDK 8.
I've used different ways to try to pass the presets to the plugin but haven't been able to activate them.
a couple of examples of what i tried.
grails.assets.babel.options = [presets: ['es2016', 'react']]
grails.assets.babel.options.presets = ['es2016', 'react']

I get this:
2017-12-06 11:57:09,221 [http-nio-8091-exec-1] ERROR [/gdbxt].[default]  - Servlet.service() for servlet [default] in context with path [/gdbxt] threw exception [Filter execution threw an exception] with root cause
java.lang.Exception: babel-transforming ExpressionDetails.jsx failed: org.mozilla.javascript.JavaScriptException: ReferenceError: [BABEL] ExpressionDetails.jsx: Unknown option: direct.presets (file:/C:/Users/tripaa21/.m2/repository/net/errbuddy/plugins/babel-asset-pipeline/1.4.5/babel-asset-pipeline-1.4.5.jar!/asset/pipeline/babel/browser.js#11513)

Am i doing something wrong or is this plugin not made to handle presets?

**Comment by kevana** [comment]
I'm not sure exactly what version of Babel is bundled with the transformer, but [it's from August of 2015](https://github.com/errbuddy/babel-asset-pipeline/commit/4ff1a4a356e13164ad61288dd256a88e9ee46ba3#diff-3bb4db0e2e46e525e2e56034cbb31100). It's probably about time to update that if anyone's still using this.

**Comment by peh** [comment]
the babel version for DirectBabilfier is super old (some 5x) and is the latest one that works with Rhino (anything that came after that was to big to be loaded into rhino)
you should really look into using [WebpackBabelifier](https://github.com/errbuddy/babel-asset-pipeline#webpack) which supports presets (and anything else that webpack supports... and spoiler alert a webpack3 udpate is coming!)
