### ISSUE TITLE
grails 3 with java 8 

### ISSUE THREAD

**Issue by psnehal** [errbuddy/babel-asset-pipeline#23]
adding babel asset plugin into the build .gradle is giving me below error.

I was wondering if you know anything about it 
Caused by: java.lang.VerifyError: (class: babel/asset/pipeline/ApplicationLoader, method: super$2$configure signature: (Lorg/springframework/boot/builder/SpringApplicationBuilder;)Lorg/springframework/boot/builder/SpringApplicationBuilder;) Illegal use of nonvirtual function call

**Comment by peh** [comment]
what version of grails are you using?

**Comment by psnehal** [comment]
3.3.10

**Comment by psnehal** [comment]
Do u have any in depth tutorial on how should I add my babel-asset-pipeline in to the grails..
This is what i did :
1. Update build.gradle
2.update jsp with  <asset:javascript src="bundle.js" ></asset:javascript> tag 
bundle.js is created by webpack for es6 file
 But now its complaning about my other js files bootstrap.js 

babel.asset.pipeline.BabelifierException: webpack exited with 1 for bootstrap.js
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)


I have this in setting already : processJsFiles: false, but looks like it's still processing my other JS files

**Comment by peh** [comment]
in which file did you put the processJsFiles: false?

**Comment by psnehal** [comment]
in build.gradle
minifyJs = true
    minifyCss = true
    includes = ["fonts/*"]
  
          configOptions = [
                  babel: [
                          enabled: true,
                          processor: 'webpack',
                          processJsFiles: false,
                  ]
          ]
          minifyOptions = [
                  languageMode: 'ES6',
                  targetLanguage: 'ES5', //Can go from ES6 to ES5 for those bleeding edgers
                  optimizationLevel: 'SIMPLE',
          ]

**Comment by psnehal** [comment]
Adding the tag in application.yml stopped the error. but its not loading my bundle.js . I was wondering If I have to call it any other way?

**Comment by peh** [comment]
yes, check the readme it says `<babel:webpack src="file.js" />` ;)

**Comment by psnehal** [comment]
So after using everything right finally, I was able to load the javascript,, But the function from that javascript was not accessible . I made that function public window.handle_data = handle_data; using this call . Any better approach than that?

**Comment by peh** [comment]
i am not sure where this function is coming from, but it's pretty common to do those things in js

**Comment by psnehal** [comment]
I am still getting this error when I deploy war file in the production server.. It works completely fine in the developement server.. Any idea what could be error?

Caused by: java.lang.VerifyError: (class: babel/asset/pipeline/ApplicationLoader, method: super$2$configure signature: (Lorg/springframework/boot/builder/SpringApplicationBuilder;)Lorg/springframework/boot/builder/SpringApplicationBuilder;) Illegal use of nonvirtual function call

**Comment by MMesch** [comment]
I have a similar issue. Build works fine, but when I deploy on tomcat I get:

```
tomcat_1         | 04-Nov-2019 12:07:04.692 SEVERE [Catalina-utility-1] org.apache.catalina.core.StandardContext.startInternal Error during ServletContainerInitializer processing
tomcat_1         |  javax.servlet.ServletException: Failed to instantiate WebApplicationInitializer class
tomcat_1         | 	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:157)
tomcat_1         | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5120)
tomcat_1         | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
tomcat_1         | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:713)
tomcat_1         | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
tomcat_1         | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
tomcat_1         | 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
tomcat_1         | 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1850)
tomcat_1         | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
tomcat_1         | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
tomcat_1         | 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
tomcat_1         | 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
tomcat_1         | 	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
tomcat_1         | 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
tomcat_1         | 	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1621)
tomcat_1         | 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:305)
tomcat_1         | 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
tomcat_1         | 	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1149)
tomcat_1         | 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1351)
tomcat_1         | 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1355)
tomcat_1         | 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1333)
tomcat_1         | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
tomcat_1         | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
tomcat_1         | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
tomcat_1         | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
tomcat_1         | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
tomcat_1         | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
tomcat_1         | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
tomcat_1         | 	at java.lang.Thread.run(Thread.java:748)
tomcat_1         | Caused by: java.lang.VerifyError: (class: babel/asset/pipeline/ApplicationLoader, method: super$2$configure signature: (Lorg/springframework/boot/builder/SpringApplicationBuilder;)Lorg/springframework/boot/builder/SpringApplicationBuilder;) Illegal use of nonvirtual function call
```

I added this to my `build.gradle`:

```
compile 'net.errbuddy.plugins:babel-asset-pipeline:2.0.6'
```

I also added these lines to my `application.yml:

```
grails:
    assets:
        babel:
            enabled: true,
            processJsFiles: false
```

I am on:
```
| Grails Version: 4.0.0 
| JVM Version: 1.8.0_222
```
and then deploy with docker on `image: tomcat:9.0-jre8-alpine`

When I remove the plugin I can deploy fine.

**Comment by peh** [comment]
Hey @MMesch 
this plugin is not tested on grails 4 nor tomcat9. Not sure whether i'll find time soon to do that^^

**Comment by MMesch** [comment]
ok, thanks for the quick answer!
